-- for MySQL

DROP TABLE IF EXISTS `blog_posts`;
CREATE TABLE `blog_posts` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`title` VARCHAR(255) NOT NULL,
	`text` TEXT NOT NULL,
	`create_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modify_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`tags` TEXT NOT NULL,
	`published` BOOLEAN NOT NULL DEFAULT TRUE
) ENGINE = InnoDB;

DROP TABLE IF EXISTS `blog_parameters`;
CREATE TABLE `blog_parameters` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`password_hash` VARCHAR(255) NOT NULL,
	`posts_on_page` INT UNSIGNED NOT NULL DEFAULT 10,
	`maximal_width_of_images` INT UNSIGNED NOT NULL DEFAULT 640,
	`dropbox_access_token` VARCHAR(255) NOT NULL
) ENGINE = InnoDB;
